title: Andrea Delfino
email: andrea.delfino@gmail.com
description: >
  So long and thanks for all the fish!
url: "https://andreadelfino.it"
baseurl: ""

github:
    username: andreadelfino
twitter:
    username: ottimo
linkedin:
    username: andrea.delfino
facebook:
    username: andrea.delfino
flickr:
    username: andreadelfino
lastfm:
    username: _shinji_

markdown: kramdown
